### ISSUE TITLE
Question Regarding COSMIC version using getCosmicSignatures()

### ISSUE THREAD

**Issue by profsprofs1991** [dami82/mutSignatures#22]
Hi @dami82, 

More than an issue is a question regarding the getCosmicSignatures() function. I noticed when it is used, it pulls the 30 COSMIC SBS signatures, however, when you download directly from Sanger Institute, there are many more (up to SBS94, and many SBS are subdivided , eg SBS7a and SBS7b).

Wanted to know if this is part of the function subsetting to the traditional 30 SBS COSMIC signatures or if there are any way of using the other SBS Signatures. 

Thanks a lot again, the package has been extremely useful otherwise,

**Comment by dami82** [comment]
Hello. Thanks for using `mutSignatures`.
The `getCosmicSignatures()` function only supports the retrieval of _"ver. 2"_ COSMIC signatures as defined by the Sanger Institute (legacy signatures, these are a few years old). However, you can easily import and use any set of mutational signatures of interest (_e.g.,_ newer versions released by the Sanger Institute) as shown below. The following example retrieves _"ver. 3.3"_ SBS GRCh38 signatures.

1. Make sure to have the latest version of `mutSignatures` installed (>= 2.1.5. From GitHub, NOT from CRAN). 
2. Read the data table including the mutational signatures of interest, format it so that columns are signatures and rows are mutation types, and then coerce it to a `mutationSignatures` object. Please, have a look at the following code.
```
sbs_url <- "https://cog.sanger.ac.uk/cosmic-signatures-production/documents/COSMIC_v3.3.1_SBS_GRCh38.txt"
sbs_df <- read.delim(sbs_url, as.is = TRUE)
rownames(sbs_df) <- sbs_df$Type
sbs_df <- sbs_df [, -1]
sbs_mutSig <- mutSignatures::as.mutation.signatures(sbs_df)
```
3. You now have a `mutationSignatures` object (`sbs_mutSig`) that you can use in your downstream analyses.

**Comment by profsprofs1991** [comment]
Great, thank you so much.
